### ISSUE TITLE
Improve ./tup to support multi dependency 

### ISSUE THREAD

**Issue by samanthajayasinghe** [derschatta/totara-docker-dev#3]
Currently './tup {name}' spin-up all available PHP containers but it's not necessary all the times. I think it's better to mention all dependency and spin-up only relevant containers.
```bash
#spin-up php71 and pgsql
./tup pgsql php-7.1

#spin-up php71, pgsql and mysql
./tup pgsql mysql php-7.1

```

**Comment by derschatta** [comment]
I tried but unfortunately it doesn't work. Nginx won't start if one of the PHP fpm backends is not there. So Nginx depends on all the php containers.
